<?php
/*
  $Id$

  generated by: 
  https://oscompose.com (c)2018

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2018 osCommerce

  Released under the GNU General Public License
*/


?>

  
    <div id="carousel" class="col-sm-<?php echo $content_width; ?> tpl_cm_carousel_rotator"> 
    
<?php echo $carousel; ?>
</div>




